### PR TITLE
First approach to allow multiple transitions

### PR DESCRIPTION
**Pull request by mancas**

### CODE REVIEW

**Comment by mancas** [comment]
I've opened this PR to discuss this approach of multiple transitions

**Comment by etiennesegonzac** [comment]
Thanks for taking the time to shape up a pull request :) Let's discuss!

I think, from our previous conversation, that our use case here is

``` javascript
window.maestro.transition(() =>  {
  this.dispatch('animationstart');
  classes.window.add('animate-out');
}, this.els.window, end).then(() => {
  window.maestro.transition(() => {
    classes.background.add('animate-out');
  }, self.els.background, end).then(() => {
    classes.window.remove('animate-out', 'animate-in');
    classes.background.remove('animate-out', 'animate-in');
    background.classList.remove('circular');
    background.style = '';
    self.dispatch('animationend');
    if (callback) { callback(); }
  });
});
```

with the current API, my suggestion for this would be to do something like

``` javascript
var animateWindow = () => {
  return window.maestro.transition(() =>  {
    classes.window.add('animate-out');
  }, this.els.window, end)
};
var animateBackground = () => {
  return window.maestro.transition(() => {
    classes.background.add('animate-out');
  }, this.els.background, end);
};
var cleanUp = () => {
  return window.maestro.mutation(() => {
    classes.window.remove('animate-out', 'animate-in');
    classes.background.remove('animate-out', 'animate-in');
    background.classList.remove('circular');
    background.style = '';
  });
};
var finish = () => {
  this.dispatch('animationend');
  if (callback) { callback(); }
};

this.dispatch('animationstart');
animateWindow()
  .then(animateBackground)
  .then(cleanUp)
  .then(finish);
```

What would this code look like with your proposed API change?

**Comment by mancas** [comment]
New code look:

``` javascript
var animateWindow = {
  block: {
    classes.window.add('animate-out');
  },
  elm: this.els.window,
  evt: end};

var animateBackground = {
  block: {
    classes.background.add('animate-out');
  },
  elm: this.els.background,
  evt: end};

var cleanUp = () => {
  return window.maestro.mutation(() => {
    classes.window.remove('animate-out', 'animate-in');
    classes.background.remove('animate-out', 'animate-in');
    background.classList.remove('circular');
    background.style = '';
  });
};
var finish = () => {
  this.dispatch('animationend');
  if (callback) { callback(); }
};

this.dispatch('animationstart');
window.maestro.transition([animateWindow, animateBackground])
  .then(cleanUp)
  .then(finish);
```

These changes don't add an important value to the API so feel free to discard them =)

**Comment by etiennesegonzac** [comment]
Thanks for the reply, it's much clearer for me now.
It is indeed just a bit of sugar but I'm not opposed to it!

I need to extract the `transition` method internals anyway because "feedbacks" are going to get their own API call (currently the `feedback` flag is a bit clumsy and it forces you to set the `timeout` parameter on the call).

Leaving the PR open so we revisit this proposal once the extraction is done. I think we may want to add it as something like `scheduler.sequence()`.

Cheers!

**Comment by etiennesegonzac** [comment]
will close this one for now

**Pull request closed without merging**
