### PR TITLE
Fixing issue #35 - tracking the direct block elements with a Map instead of a broken Object.

### LINKED ISSUE #35: Attaching a 'scroll' event on more than one element doen't work

### PR DESCRIPTION
**Pull request by etiennesegonzac**
Closes #35

### CODE REVIEW

**Comment by wilsonpage** [comment]
Looks good! Ship it :dancers:

**Comment by wilsonpage** [comment]
@etiennesegonzac we need a new version stamping for this, I don' think I have permissions.

**Comment by etiennesegonzac** [comment]
Already done it (I think)etiennesegonzac/dom-scheduler wrote:@etiennesegonzac we need a new version stamping for this, I don' think I have permissions.

—Reply to this email directly or view it on GitHub.

Sent Using Firefox OS

**Comment by wilsonpage** [comment]
Ah you're right. Thanks!

**Comment by wilsonpage** [comment]
Ah spotted the issue. Semver must always be have three segments `major.minor.patch`. The tags you have pushed only have two segments `major.minor`. Could you re-tag and push?

**Comment by wilsonpage** [comment]
So `v0.1.0` -> `v0.1.0` etc

**Comment by wilsonpage** [comment]
TYPO: So `v0.1` -> `v0.1.0` etc

**Pull request merged**
